### ISSUE TITLE
S_DUNGEON_CAMERA_SET

### ISSUE THREAD

**Issue by bigmama90** [meishuu/tera-data#171]

**Comment by Mister-Kay** [comment]
Region? EU?

**Comment by bigmama90** [comment]
yes Region EU

do you need more infos what Proxy is sayin?

**Comment by bigmama90** [comment]
[22:17:07 GMT+0200] ERROR tera-proxy-game: [dispatch] write: failed to generate
S_DUNGEON_CAMERA_SET<*>
error: [protocol] write ("S_DUNGEON_CAMERA_SET"): invalid code "null"'

**Comment by Mister-Kay** [comment]
Jest got fixed. Update your tera-data, and you should be good.
