### ISSUE TITLE
HH marker does not work

### ISSUE THREAD

**Issue by terarian** [meishuu/tera-data#305]
Hi,

I used to use Solar91's HH-firewall-marker [Link here](https://github.com/soler91/HH-Firewall-Markers) but since last week's patch, it started stop working. I was waiting on updated version of Tera-data here, but it seems HH-marker module still does not work even with updated tera-data.

This is the error msg on my proxy window (cmd)

<img src=https://puu.sh/yJgCF/34e7d6d8cb.png>

I am not very good at scripting. Could you fix this issue? or is there anything wrong on module itself instead of tera-data?

**Comment by Mister-Kay** [comment]
Because signs are not available on NA, that packet cannot be found for that region. The module will need to use some other marker for NA.

**Comment by TeraProxy** [comment]
S_SPAWN_BUILD_OBJECT is in NA's map file. He probably plays on some other region that didn't map it. Question is from December (last patch) which makes this even more likely.

@terarian You need to map the opcode yourself or find someone that can do it. They need to be mapped for each region separately so if you are not playing on NA or EU some stuff might be missing. The following tutorial explains it quite beginner friendly: https://github.com/beng-mods/opcodes-4-dummies
