### ISSUE TITLE
protocol.324671.map MISSING OP CODES

### ISSUE THREAD

**Issue by Moorleiche** [meishuu/tera-data#317]
Hey someone got OP Codes for:
- S_CURRENT_CHANNEL
- C_SELECT_CHANNEL

**Comment by Moorleiche** [comment]
S_PREPARE_SELECT_CHANNEL = 45961
C_LIST_CHANNEL = 63634
C_SELECT_CHANNEL = 20252
S_CURRENT_CHANNEL = 37097

**Comment by scarfcat** [comment]
https://github.com/beng-mods/opcodes-4-dummies

**Comment by Moorleiche** [comment]
nice work! issue can be closed!
