### ISSUE TITLE
update problems

### ISSUE THREAD

**Issue by AETM132** [meishuu/tera-data#346]
![errortcc](https://user-images.githubusercontent.com/34170841/37543940-a91d5330-2939-11e8-9136-2b81a2357d30.PNG)
Hello, idk why i have this problem. i can't download the last version.

**Comment by Mister-Kay** [comment]
@Foglio1024 halp xD

**Comment by Foglio1024** [comment]
TCC issues here -> https://github.com/Foglio1024/Tera-custom-cooldowns/issues

Btw just try again or download it manually if it still fails.
