### ISSUE TITLE
Ever since the new update came the proxy stopped working for me

### ISSUE THREAD

**Issue by aeriazip** [meishuu/tera-data#64]
So ever since the last 2 updates of tera data came in the proxy has just stopped working here is a print screen http://prntscr.com/eo5d0h of what it says when i log into tera i blurred out name and IP for obvious reasons, but if you could help me with this issue would be greatly appreciated

**Comment by pinkipi** [comment]
Those scripts will need to change `require('tera-data')` to `require('tera-data-parser')`, since those two modules were recently separated.
