### ISSUE TITLE
Field definitions sometimes confusing

### ISSUE THREAD

**Issue by Gl0** [meishuu/tera-data#7]
`uint64 target` in some packets are actually a creature id, but in other it is `uint32 serverid` + `uint32 playerid` combo field, which in another packets called as `uint64 pid`

**Comment by reiv** [comment]
I think for consistency and ease of use it would be best to treat this field as a single `uint64` (you can always extract the high and low bits later if you need them). As for naming, it really depends on the context of the packet. For instance, `target` conveys more information than `pid`. What do you think, @meishuu?

**Comment by Gl0** [comment]
Main confusion is what object is referenced by target, player or creature.

**Comment by reiv** [comment]
Oh, I see. For some packets, it could be either one, couldn't it? AFAIK the only way of telling the difference is checking if the referenced object was spawned by `sSpawnNPC` or `sSpawnUser` / `sSpawnMe`. Is that wrong?

**Comment by Gl0** [comment]
Think it depends only on packet type. For S_ADD_CHARM_STATUS target is creature but for S_PARTY_MEMBER_CHARM_ADD target is player. 
btw guid packets use only uint32 playerid part without serverid.

**Comment by reiv** [comment]
What exactly do you mean when you say creature? I thought you were referring to NPCs/mobs.  Charms can only apply to players.

To give a counterexample, the target field in `cCanLockonTarget` and `sCanLockonTarget` can be a player or non-player entity.

Also, what are guid packets?

**Comment by Gl0** [comment]
When you receive S_SPAWN_USER, it contains both global unique server&player id (across all players on all servers) and session unique creature id (across all entities, including players, NPCs, minions, projectiles...). Which list you need to lookup to find target? For S_PARTY_MEMBER_CHARM_ADD you need first one, for S_ADD_CHARM_STATUS - second.

Guild packets - all S_GUILD_*. Guilds are server specific, so all related structures doesn't contain server id.

**Comment by reiv** [comment]
Thanks for the clarification. That makes a lot of sense! I was wondering why the S_PARTY_* packets all used a different id than the "server-local" ones. But I can see how cross-server party matching would necessitate those ids being unique on all servers. In that case, you are right in that the naming of those fields needs to be more explicit.

I was going to suggest `guid` or `uuid`... but that usually implies 128 bits. Perhaps `playerID` to denote the combination of server id and player id, and `entityID` for local ids? Actually, it'd be pretty cool if those could be defined as separate field types, so the names can still describe their purpose.

**Comment by Gl0** [comment]
You can always put a comment to describe either purpose or type clarification.

**Comment by alexrp** [comment]
@Gl0 are there still any fields that are incorrectly defined like this? Or can we close this issue?

**Comment by Gl0** [comment]
Mentioned fields are still named the same. They are probably widely used in many scripts already, and anyone who use them - understand their meaning. For newbies that may be a problem, but generally it's not so hard to look at live packet and see which one is used.

**Comment by alexrp** [comment]
I'm not referring to names; what I'm referring to is using a `uint64` where the value is actually `uint32` server ID + `uint32` player ID. In that case, we should change the definition because it's just flat out wrong. I'm not so worried about names because we'll soon get a way to specify a specific type (e.g. `creatureid` instead of `uint64`).

**Comment by Gl0** [comment]
That thing is also the same.

**Comment by alexrp** [comment]
@Gl0 I've addressed the ones I could find in c3925308c4021ba1be34bd832786f63fcd71f0f3. Any others?

**Comment by Gl0** [comment]
All S_PARTY_MEMBER_ABNORMAL* packets

**Comment by alexrp** [comment]
Done: 3d78219dcd26b39cd8ce450aedbdda35be66a463

**Comment by Gl0** [comment]
Can't remember other packets with that issue.

**Comment by meishuu** [comment]
This seems like it's resolved so I'll do some spring cleaning and close this.
